<?php

namespace App\Console\Commands;

use App\Models\MasterDatasetProcess;
use App\Support\MasterDatasetAssignmentService;
use App\Support\MasterDatasetExportCoordinator;
use Illuminate\Console\Command;

class RebuildAssignments extends Command
{
    protected $signature = 'dataset:rebuild {processId? : The ID of the dataset process to rebuild} {--exports : Also regenerate exports synchronously}';

    protected $description = 'Re-run assignment rules for a dataset process and optionally regenerate exports.';

    public function handle(MasterDatasetAssignmentService $assignmentService, MasterDatasetExportCoordinator $exportCoordinator): int
    {
        $processId = $this->argument('processId');

        $process = null;
        if ($processId) {
            $process = MasterDatasetProcess::find($processId);
        } else {
            $process = MasterDatasetProcess::orderByDesc('id')->first();
        }

        if (! $process) {
            $this->error('No dataset process found. Provide a valid {processId}.');
            return 1;
        }

        $this->info(sprintf('Rebuilding assignments for process #%d (token=%s)...', $process->id, $process->token));
        $assignmentService->assign($process);
        $this->info('Assignments updated.');

        $this->info('Queuing exports refresh...');
        $exportCoordinator->ensureFresh($process);

        if ($this->option('exports')) {
            $this->info('Generating exports synchronously...');
            $exportCoordinator->generateExports($process);
            $this->info('Exports generated.');
        } else {
            $this->info('Exports will be generated by the queue worker.');
        }

        return 0;
    }
}
